New Test
jotform/zenith pull request #33
Opened 2023-04-15 10:02 UTC by alpaylan

I added a new test that works over a randomized file tree with random file names/structures/sizes.

2023-04-24 07:48 UTC, hmdoganjf requested changes

2023-04-24 07:48 UTC, hmdoganjf commented on tests/Hasher.spec.js
> +  it("Should be fun", () => {
It would be awesome if this was named meaningfully

2023-04-24 07:49 UTC, hmdoganjf commented
Other than the small bits about code style, awesome job, thanks a lot!

2023-04-24 18:44 UTC, alpaylan commented on tests/Hasher.spec.js
> +const genStr = (_size) => {
I moved them into `test/utils.js`

2023-04-25 06:11 UTC, hmdoganjf approved these changes

2023-04-25 06:12 UTC, merged